### ISSUE TITLE
Leadership goes blank with no data

### ISSUE THREAD

**Issue by Guruleenyc** [michaelmaw/spiceworks-hdpp#10] opened 2016-09-29 17:18 UTC
The Leadership Bar failed after two days! Was working for a couple days and then the gray bar is still present but w/o data. I tried toggle it off/on and it did not fix it. We are running 7.5.0093.

Any ideas?

**Comment by TekkenIronfist** [comment] 2016-10-07 10:20
Same issue here. On Spiceworks 7.5.00088
If I leave Leaderboard and Ranking unchecked the Closed count per 7 days & 30 days displays but as soon as I tick either one of the other options (or both) it will disappear.

**Comment by michaelmaw** [comment] 2017-01-02 21:12
Can you provide a few more details about your environment - ie. browser & version?

Also, if you disable all your other SW plugins temporarily and the flush your browser cache, do you still have this problem?

**Comment by David-Lotus** [comment] 2017-01-30 17:14
I have the same issue with mine as well, Production system, Spiceworks 7.5.00098 and HDPP Version 3.4. Chrome and IE 11. Come back for a short while and then vanishes again. All other plugins disabled (due to another issue I was troubleshooting with Spiceworks Support)

**Comment by michaelmaw** [comment] 2017-01-31 19:06
@David-Lotus Sounds like another SW event is refreshing the HTML DOM and the plugin isn't detecting when this happens. I'll do some more testing on my end to see if I can replicate this. Thanks for the feedback.

**Comment by David-Lotus** [comment] 2017-02-02 14:23
@michaelmaw Thanks, much appreciated, very well liked plugin over here, if you need anything else please let me know.

**Comment by David-Lotus** [comment] 2017-02-06 15:40
Just an update, I had another issue with SW and the SW support guys had a look, they gave me a repair script to run and after I ran it the Leader board seems to be working ok.

**Comment by michaelmaw** [comment] 2017-02-06 22:02
Interesting! So this is potentially an issue with Spiceworks itself and not this plugin? Do you know what the repair script actually fixed?

**Comment by David-Lotus** [comment] 2017-02-08 08:26
I have a log file that you can take a look at if you want, I've had a quick look through and can't see any personally or corporate identifiable information, so i'll email it to you if you provide an email address...

**Comment by michaelmaw** [comment] 2017-02-08 17:52
@David-Lotus Please send the log file to support@michaelmaw.com and I'll review it. Thanks.

**Comment by David-Lotus** [comment] 2017-02-15 16:20
@michaelmaw  Sent, sorry for the delay.

**Comment by isha-12** [comment] 2017-07-11 13:42
I am having the same issue, the leaderboard is gone with 
Spiceworks Version 7.5.00101
I tried, firefox, chrome and IE. I reinstalled the plugin and nothing. Any solution for this?

**Comment by michaelmaw** [comment] 2017-07-12 06:06
@isha-12 I'm interested to know if this happened after you added a new user to your Spiceworks install. Do recall if this happened around the same time? Just trying to figure out what changed in your installation that may have caused this.

**Comment by isha-12** [comment] 2017-07-12 14:20
I really just came in to work and it was gone, I dont remember making any modifications at all to users or anything like that. Not sure if anything happened over night but I tried reinstalling the plugin and removing all configuration and re-adding it back, everything else works except for that part, checked or unchecked it does not show. This is a very useful feature for me. I really wish it worked. I contacted SW and they just told me to contact the developer. I explained to the them about the previous post and the possible script solution but I got no answer after that, let me know if I need to provide you anything to help me with this
I appreciate it

**Comment by TekkenIronfist** [comment] 2017-07-12 14:52
Still happens intermittently with me. It looks like it may be related to
merging tickets. I think I see it disappear and reappear coincidentally
after merging duplicates - however it's not every time.

**Comment by michaelmaw** [comment] 2017-07-14 18:09
@TekkenIronfist That's helpful, I may have to add in an additional event handler to reinitialize the leaderboard after a merge occurs.

@isha-12 Not sure what would have made it randomly stop working if no changes were made on your end. I suspect something must have changed, but difficult to troubleshoot when we don't know what. I'll review the code and see if I can spot anything that might produce an error due to an unexpected data response from the API.

**Comment by isha-12** [comment] 2017-07-14 20:10
I will keep an eye when merging tickets. My suddenly starting appearing again as well.

**Comment by michaelmaw** [comment] 2017-09-07 20:58
Good news! We've made a breakthrough and identified the cause of this problem - if you have any "Closed" tickets that are not assigned to a tech, then that appears to break the leaderboard and prevent it from showing.

I'm reviewing the code to find out why that is happening and will release a fix for this. Thanks to David from Lotus Group for helping to identify the exact cause.

**Closed as completed** 2017-09-08 03:08 UTC
Labels: bug
